<?php
$title = 'Liste des préférences';
$this->headTitle($title);
?>
<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?> 
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a href="<?php echo $this->url('preference/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs">Ajouter une nouvelle préférence</a>
</p>
<table class="table table-striped">  
    <tr>
        <th>Attribut de la préférence</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($preferences as $preference) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($preference->getPrefAttribute()) ?>
            </td>
            <td>
                <a href="<?= $this->url('preference/show', ['id' => $this->escapeUrl($preference->getPrefId())]) ?>" class="btn btn-primary btn-xs">Détails</a>
            </td>
            <td>
                <a href="<?= $this->url('preference/update', ['id' => $this->escapeUrl($preference->getPrefId())]) ?>" class="btn btn-warning btn-xs">Modifier</a>
            </td>
            <td>
                <a href="<?= $this->url('preference/delete', ['id' => $this->escapeUrl($preference->getPrefId())]) ?>" class="btn btn-danger btn-xs">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>