<?php $this->headTitle($this->translate('Détails d\'une préférence')); ?>
<h2><?= $this->translate('Détails d\'une préférence') ?></h2>

<p>
    <?= $this->translate('Attribut de la préférence :') ?> <?php echo $this->escapeHtml($preference->getPrefAttribute()) ?>
</p>

<?php if ($preference->getFkPrefUser() != null) : ?>
    <p>
        <?= $this->translate('User :') ?> <?php echo $this->escapeHtml($preference->getFkPrefUser()->getUserLogin()) ?>
    </p>
<?php endif; ?>

<?php if ($preference->getFkPrefService() != null) : ?>
    <p>
        <?= $this->translate('Service :') ?> <?php echo $this->escapeHtml($preference->getFkPrefService()->getServiceName()) ?>
    </p>
<?php endif; ?>

<?php if ($preference->getFkPrefStatus() != null) : ?>
    <p>
        <?= $this->translate('Status :') ?> <?php echo $this->escapeHtml($preference->getFkPrefStatus()->getStatusName()) ?>
    </p>
<?php endif; ?>

<?php if ($preference->getFkPrefProfile() != null) : ?>
    <p>
        <?= $this->translate('Profil :') ?> <?php echo $this->escapeHtml($preference->getFkPrefProfile()->getProfileName()) ?>
    </p>
<?php endif; ?>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($preference->getPrefLastUpdate() != null) {
        echo $preference->getPrefLastUpdate()->format('d-m-Y H:i:s');
    } else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>
<a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/preference'); ?>"><?= $this->translate('Retour') ?></a>