<?php

namespace DoctrineORMModule\Proxy\__CG__\Ent\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EntProfile extends \Ent\Entity\EntProfile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileId', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileLdap', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileName', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileLibelle', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileDescription', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileLastUpdate', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'fkUpUser');
        }

        return array('__isInitialized__', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileId', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileLdap', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileName', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileLibelle', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileDescription', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'profileLastUpdate', '' . "\0" . 'Ent\\Entity\\EntProfile' . "\0" . 'fkUpUser');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EntProfile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProfileId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProfileId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileId', array());

        return parent::getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileLdap($profileLdap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileLdap', array($profileLdap));

        return parent::setProfileLdap($profileLdap);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileLdap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileLdap', array());

        return parent::getProfileLdap();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileName($profileName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileName', array($profileName));

        return parent::setProfileName($profileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileName', array());

        return parent::getProfileName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileLibelle($profileLibelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileLibelle', array($profileLibelle));

        return parent::setProfileLibelle($profileLibelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileLibelle', array());

        return parent::getProfileLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileDescription($profileDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileDescription', array($profileDescription));

        return parent::setProfileDescription($profileDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileDescription', array());

        return parent::getProfileDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileLastUpdate($profileLastUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileLastUpdate', array($profileLastUpdate));

        return parent::setProfileLastUpdate($profileLastUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileLastUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileLastUpdate', array());

        return parent::getProfileLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function addFkUpUser(\Doctrine\Common\Collections\Collection $fkUpUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFkUpUser', array($fkUpUser));

        return parent::addFkUpUser($fkUpUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFkUpUser(\Doctrine\Common\Collections\Collection $fkUpUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFkUpUser', array($fkUpUser));

        return parent::removeFkUpUser($fkUpUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUpUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUpUser', array());

        return parent::getFkUpUser();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($hydrator, $owner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($hydrator, $owner));

        return parent::toArray($hydrator, $owner);
    }

}
