<?php
$title = "Ajout d'un module";
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate'))?>
<div class="form-group<?php if($form->get('moduleName')->getMessages()) echo ' has-error'; ?>">
    <?=$this->formLabel($form->get('moduleName')->setLabelAttributes(['class' => 'col-sm-2 control-label']))?>
    <div class="col-sm-10">
        <?=$this->formText($form->get('moduleName')->setAttribute('class', 'form-control'))?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?=$this->formElementErrors($form->get('moduleName'))?>           
    </div>
</div>
<div class="form-group<?php if($form->get('moduleLibelle')->getMessages()) echo ' has-error'; ?>">
    <?=$this->formLabel($form->get('moduleLibelle')->setLabelAttributes(['class' => 'col-sm-2 control-label']))?>
    <div class="col-sm-10">
        <?=$this->formText($form->get('moduleLibelle')->setAttribute('class', 'form-control'))?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?=$this->formElementErrors($form->get('moduleLibelle'))?>           
    </div>
</div>
<div class="form-group<?php if($form->get('moduleDescription')->getMessages()) echo ' has-error'; ?>">
    <?=$this->formLabel($form->get('moduleDescription')->setLabelAttributes(['class' => 'col-sm-2 control-label']))?>
    <div class="col-sm-10">
        <?=$this->formTextarea($form->get('moduleDescription')->setAttribute('class', 'form-control'))?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?=$this->formElementErrors($form->get('moduleDescription'))?>           
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>