<?php $this->headTitle($this->translate('Liste des modules')); ?>

<h1><?= $this->translate('Liste des modules') ?></h1>

<p>
    <a href="<?php echo $this->url('module/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter un nouvel module') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?> 

<table class="table table-striped">  
    <tr>
        <th><?= $this->translate('Nom du module') ?></th>
        <th><?= $this->translate('Libellé') ?></th>
        <th><?= $this->translate('Description') ?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($listModules as $module) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($module->getModuleName()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($module->getModuleLibelle()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($module->getModuleDescription()) ?>
            </td>
            <td>
                <a href="<?= $this->url('module/show', ['id' => $this->escapeUrl($module->getModuleId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('module/show/update', ['id' => $this->escapeUrl($module->getModuleId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('module/show/delete', ['id' => $this->escapeUrl($module->getModuleId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>