<?php $this->headTitle($this->translate('Détails d\'un module')); ?>

<h2><?= $this->translate('Détails d\'un module') ?></h2>
<p>
    <?= $this->translate('Nom du module :') ?> <?= $this->escapeHtml($module->getModuleName()) ?>
</p>
<p>
    <?= $this->translate('Libellé du module :') ?> <?= $this->escapeHtml($module->getModuleLibelle()) ?>
</p>
<p>
    <?= $this->translate('Description du module :') ?> <?php echo $this->escapeHtml($module->getModuleDescription()) ?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($module->getModuleLastUpdate() != null) {
        echo $module->getModuleLastUpdate()->format('d-m-Y H:i:s');
    }
    else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>

<a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/module'); ?>"><?= $this->translate('Retour') ?></a>