<?php $this->headTitle($this->translate('Liste des users')); ?>

<h1><?= $this->translate('Liste des users') ?></h1>

<p>
    <a href="<?= $this->url('user/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter un nouvel user') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m) : ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>  
    </div> 
<?php endforeach; ?>

<table class="table table-striped">
    <tr>
        <th><?= $this->translate('Login') ?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($user->getUserLogin()) ?>
            </td>
            <td>
                <a href="<?= $this->url('user/show', ['id' => $this->escapeUrl($user->getUserId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('user/show/update', ['id' => $this->escapeUrl($user->getUserId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('user/show/delete', ['id' => $this->escapeUrl($user->getUserId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
