<?php $this->headTitle($this->translate('Liste des users')); ?>

<h1><?php echo $this->translate('Liste des users') . ' : ' . count($users) ?></h1>

<p>
    <a href="<?= $this->url('zfcadmin/user/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter un nouvel user') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m) : ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>  
    </div> 
<?php endforeach; ?>
<div class="input-group col-lg-3 pull-right">
    <input id="filterTable" type="text" class="form-control" placeholder="<?= $this->translate('Search for... ou faible...') ?>">
    <span class="input-group-addon"><?= $this->translate('Magic !') ?></span>
</div>
<table class="table table-striped" >

    <!--           data-detail-view="true"
               data-detail-formatter="detailFormatter"-->
    <thead>
        <tr>
            <th><?= $this->translate('Login') ?></th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th> 
            <th>&nbsp;</th>        
        </tr>
    </thead>
    <tbody  class="searchable">
        <?php foreach ($users as $user) : ?>
            <tr>
                <td>
                    <?= $this->escapeHtml($user->getUserLogin()) ?>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/profile/show/profiling', ['id' => $this->escapeUrl($user->getUserId())]); ?>" class="btn btn-warning btn-xs"><?= $this->translate('Mettre à jour les profils de l\'user') ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/user/show', ['id' => $this->escapeUrl($user->getUserId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/user/show/update', ['id' => $this->escapeUrl($user->getUserId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/user/show/delete', ['id' => $this->escapeUrl($user->getUserId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
