<?php $this->headTitle($this->translate('Détails d\'un user')); ?>

<h2><?= $this->translate('Détails d\'un user') ?></h2>

<p>
    <?= $this->translate('Login :') ?> <?= $this->escapeHtml($user->getUserLogin()) ?>
</p>

<p>
    <?= $this->translate('Dernière connexion :') ?> 
    <?php
    if ($user->getUserLastConnection() != null) {
        echo $user->getUserLastConnection()->format('d-m-Y H:i:s');
    }
    ?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($user->getUserLastUpdate() != null) {
        echo $user->getUserLastUpdate()->format('d-m-Y H:i:s');
    }
    else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>

<p>
    <?= $this->translate('Status :') ?> <?php echo $user->getUserStatus() ?>
</p>

<p>
    <?= $this->translate('Rôle :') ?> 
    <?php
    foreach ($user->getFkUrRole() as $role) {
        if ($role->getName()) :
            echo $this->escapeHtml($role->getName());
            echo ' - ';
            echo $this->escapeHtml($role->getName());
        endif;
    }
    ?>
</p>

<p>
    <?= $this->translate('Status :') ?> 
    <?php
    foreach ($user->getFkUpProfile() as $profile) {
        if ($profile->getProfileName()) :
            echo $this->escapeHtml($profile->getProfileName());
            echo ' - ';
            echo $this->escapeHtml($profile->getProfileLdap());
            echo '<br />';
        endif;
    }
    ?>
</p>

<a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/user'); ?>"><?= $this->translate('Retour') ?></a>
