<?php $this->headTitle($this->translate('Liste des type de listes')); ?>

<h1><?= $this->translate('Liste des type de listes') ?></h1>

<p>
    <a href="<?= $this->url('zfcadmin/listtype/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter un nouveau type de list') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m) : ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>  
    </div> 
<?php endforeach; ?>
<div class="input-group col-lg-3 pull-right">
    <input id="filterTable" type="text" class="form-control" placeholder="<?= $this->translate('Catch Me If You Can') ?>">
    <span class="input-group-addon"><?= $this->translate('Cheat !') ?></span>
</div>
<table class="table table-striped" >

    <!--           data-detail-view="true"
               data-detail-formatter="detailFormatter"-->
    <thead>
        <tr>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Label') ?></th>
            <th><?= $this->translate('Description') ?></th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>        
        </tr>
    </thead>
    <tbody  class="searchable">
        <?php foreach ($listtypes as $listtype) : ?>
            <tr>
                <td>
                    <?= $this->escapeHtml($listtype->getListtypeLibelle()) ?>
                </td>
                <td>
                    <?= $this->escapeHtml($listtype->getListtypeName()) ?>
                </td>
                <td>
                    <?= $this->escapeHtml($listtype->getListtypeLibelle()) ?>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/listtype/show', ['id' => $this->escapeUrl($listtype->getListtypeId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/listtype/show/update', ['id' => $this->escapeUrl($listtype->getListtypeId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/listtype/show/delete', ['id' => $this->escapeUrl($listtype->getListtypeId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
