<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <?=$this->headMeta()?>
        <?=$this->headTitle('ENT')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <!--<link rel="stylesheet" href="<?//=$this->basePath('lib/css/bootstrap.css')?>">-->
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath('styles/style.css'))
                        ->prependStylesheet($this->basePath('lib/css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('lib/css/bootstrap.min.css')) ?>
        <?=$this->headLink()?>
        
        <?=$this->headStyle()?>
        
        <?=$this->headScript()?>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('home')?>">ENT</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Index <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?=$this->url('index')?>">Index</a></li>
                               <li><a href="<?=$this->url('action')?>">Action</a></li>
                               <li><a href="<?=$this->url('attribute')?>">Attribut</a></li>
                               <li><a href="<?=$this->url('contact')?>">Contact</a></li>
                               <li><a href="<?=$this->url('module')?>">Module</a></li>
                               <li><a href="<?=$this->url('permission')?>">Permission</a></li>
                               <li><a href="<?=$this->url('preference')?>">Préférence</a></li>
                               <li><a href="<?=$this->url('profile')?>">Profil</a></li>
                               <li><a href="<?=$this->url('service')?>">Service</a></li>
                               <li><a href="<?=$this->url('status')?>">Status</a></li>
                               <li><a href="<?=$this->url('user')?>">Utilisateur</a></li>
                               <li><a href="<?=$this->url('version')?>">Version</a></li>
                            </ul>
                        </li>
                    </ul>
<!--                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Link</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </li>
                    </ul>-->
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
        
        <div class="container">
            <?=$this->content?>
        </div>
        
                <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('lib/js/bootstrap.min.js'))
            ->prependFile($this->basePath('lib/js/jquery.min.js'))
            ->prependFile($this->basePath('lib/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('lib/js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
<!--        <script src="<?//=$this->basePath('lib/js/jquery.min.js')?>"></script>
        <script src="<?//=$this->basePath('lib/js/bootstrap.min.js')?>"></script>-->
        <?=$this->inlineSCript()?>
    </body>
</html>
