<h2><?=$this->translate('Ajouter un service attribute')?></h2>
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate')) ?>
<div class="form-group<?php if ($form->get('serviceAttributeValue')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('serviceAttributeValue')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('serviceAttributeValue')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('serviceAttributeValue')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('fkSaService')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('fkSaService')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?php
        echo $this->formSelect($form->get('fkSaService')->setLabelAttributes(['class' => '']))
        ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('fkSaService')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('fkSaAttribute')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('fkSaAttribute')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?php
        echo $this->formSelect($form->get('fkSaAttribute')->setLabelAttributes(['class' => '']))
        ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('fkSaAttribute')) ?>           
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary"><?=$this->translate('Ajouter')?></button>
    </div>
</div>
<?=$this->form()->closeTag()?>