<?php $this->headTitle($this->translate('Liste des services attributes')); ?>

<h1><?=$this->translate('Liste des attributes')?></h1>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m) : ?>
    <?=$this->translate($m)?>  
<?php endforeach; ?>
<p>
    <a href="<?php echo $this->url('service-attribute/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs">Ajouter un nouveau service attribut</a>
</p>

<table class="table table-striped">
    <?php foreach ($servicesAttributes as $service) : ?>
        <tr>
            <td>
                <?=$this->escapeHtml($service->getFkSaService()->getServiceName())?>
            </td>
            <td>
                <?=$this->escapeHtml($service->getFkSaAttribute()->getAttributeName())?>
            </td>
            <td>
                <?=$this->escapeHtml($service->getServiceAttributeValue())?>
            </td>
            <td>
                <a href="<?=$this->url('service-attribute/show', ['id'=>$this->escapeUrl($service->getServiceAttributeId())])?>" class="btn btn-primary btn-xs"><?=$this->translate('Détails')?></a>
            </td>
            <td>
                <a href="<?=$this->url('service-attribute/show/modify', ['id'=>$this->escapeUrl($service->getServiceAttributeId())])?>" class="btn btn-warning btn-xs"><?=$this->translate('Modifier')?></a>
            </td>
            <td>
                <a href="<?=$this->url('service-attribute/show/delete', ['id'=>$this->escapeUrl($service->getServiceAttributeId())])?>" class="btn btn-danger btn-xs"><?=$this->translate('Supprimer')?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>