
<h2><?= $this->translate('Détails d\'un service attribute') ?></h2>

<p>
    <?= $this->translate('Service Attribut valeur :') ?> <?= $this->escapeHtml($servicesAttributes->getServiceAttributeValue()) ?>
</p>

<p>
    <?= $this->translate('Nom service :') ?> <?= $this->escapeHtml($servicesAttributes->getFkSaService()->getServiceName()) ?>
</p>

<p>
    <?= $this->translate('Nom attribut :') ?> <?= $this->escapeHtml($servicesAttributes->getFkSaAttribute()->getAttributeName()) ?>
</p>




