<h2><?=$this->translate('Ajouter un service')?></h2>
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate')) ?>
<div class="form-group<?php if ($form->get('serviceName')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('serviceName')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('serviceName')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('serviceName')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('serviceLibelle')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('serviceLibelle')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('serviceLibelle')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('serviceLibelle')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('serviceDescription')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('serviceDescription')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('serviceDescription')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('serviceDescription')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('fkCsContact')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('fkCsContact')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <div class="checkbox">
            <?php
            $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
            echo $this->formMultiCheckbox($form->get('fkCsContact')->setLabelAttributes(['class' => '']))
            ?>
        </div>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('fkCsContact')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('fkSaAttribute')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('fkSaAttribute')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <div class="checkbox">
            <?php
            $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
            echo $this->formMultiCheckbox($form->get('fkSaAttribute')->setLabelAttributes(['class' => '']))
            ?>
        </div>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('fkSaAttribute')) ?>           
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary"><?=$this->translate('Ajouter')?></button>
    </div>
</div>
<?=$this->form()->closeTag()?>