
<h2><?= $this->translate('Détails d\'un service') ?></h2>

<p>
    <?= $this->translate('Nom :') ?> <?= $this->escapeHtml($service->getServiceName()) ?>
</p>

<p>
    <?= $this->translate('Libelle :') ?> <?= $this->escapeHtml($service->getServiceLibelle()) ?>
</p>

<p>
    <?= $this->translate('Description :') ?> <?= $this->escapeHtml($service->getServiceDescription()) ?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php 
    if ($service->getServiceLastUpdate() != null) {
        echo $service->getServiceLastUpdate()->format('d-m-Y H:i:s');
    }
    ?>
</p>

<p>
    <?= $this->translate('Contact :') ?> 
    <?php
    foreach ($service->getFkCsContact() as $contact) {
        if ($contact->getContactLibelle()) :
            echo $this->escapeHtml($contact->getContactLibelle());
        endif;
    }
    ?>
</p>

<p>
    <?= $this->translate('Attribut :') ?> 
    <br>
    <?php
    foreach ($service->getFkSaService() as $sa) {
        if ($sa->getFkSaAttribute()->getAttributeName()) :
            echo $this->escapeHtml($sa->getFkSaAttribute()->getAttributeName()).' : ';
        endif;
        if ($sa->getServiceAttributeValue()) {
            echo $this->escapeHtml($sa->getServiceAttributeValue());
        } else {
            echo 'ø';
        }
        ?>
    <br>
        <?php
    }
    ?>
</p>

