<?php $this->headTitle($this->translate('Détails d\'un service')); ?>
<h2><?= $this->translate('Détails d\'un service') ?></h2>

<p>
    <?= $this->translate('Nom :') ?> <?= $this->escapeHtml($service->getServiceName()) ?>
</p>

<p>
    <?= $this->translate('Libelle :') ?> <?= $this->escapeHtml($service->getServiceLibelle()) ?>
</p>

<p>
    <?= $this->translate('Description :') ?> <?= $this->escapeHtml($service->getServiceDescription()) ?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($service->getServiceLastUpdate() != null) {
        echo $service->getServiceLastUpdate()->format('d-m-Y H:i:s');
    } else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>

<p>
    <?= $this->translate('Attribut :') ?> 
    <?php
    foreach ($service->getFkSaAttribute() as $attribute) {
        if ($attribute->getAttributeName()) {
            echo $this->escapeHtml($attribute->getAttributeName());
        }
        ?>
        <?php
    }
    ?>
</p>

<?= $this->translate('Préférence :<br />') ?> 
<dl class="dl-horizontal">
    <?php
    if ($preferenceAttribute) {
        foreach ($preferenceAttribute as $attribute) {
            echo '<dt>' . $attribute->{'attribute_name'} . '</dt>';
            echo '<dd>' . $attribute->{'attribute_value'} . '</dd>';
        }
    }
    ?> 
</dl>

<a class="btn btn-danger" href="<?php echo $this->url('service'); ?>"><?= $this->translate('Retour') ?></a>