<?php $this->headTitle($this->translate('Modifier un service')); ?>
<h2><?= $this->translate('Modifier un service') ?></h2>
<?= $this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate')) ?>
<div class="form-group<?php if ($form->get('serviceName')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('serviceName')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('serviceName')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('serviceName')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('serviceLibelle')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('serviceLibelle')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('serviceLibelle')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('serviceLibelle')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('serviceDescription')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('serviceDescription')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('serviceDescription')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('serviceDescription')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('serviceKeywords')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('serviceKeywords')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('serviceKeywords')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('serviceKeywords')) ?>           
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Attributs : </label>
    <div class="col-sm-10">
        <?php
        $i = 0;
        $formAttribute = '';
        foreach ($attributes as $attribute) {
            $getServiceAttributes = 'serviceAttributes[' . $attribute->getAttributeId() . ']';
            $valueAttribute = '';
            if (isset($_POST['serviceAttributes']) && !empty($_POST['serviceAttributes'])) {
                $valueAttribute = $_POST['serviceAttributes'][$attribute->getAttributeId()];
            } else if ($preference) {
//                foreach ($preferences as $preference) {
                if ($preference->getFkPrefService()->getServiceId() === $service->getServiceId()) {
                    $preferenceAttribute = json_decode($preference->getPrefAttribute());
                    foreach ($preferenceAttribute as $value) {
                        foreach ($value->{'serviceAttributeData'} as $att) {
                            if ($att->{'attributeId'} === $attribute->getAttributeId()) {
                                $valueAttribute = $att->{'attributeValue'};
                                break;
                            }
                        }
                    }
                }
//                }
            }
            $i++;
            if ($i === 1) {
                ?>
                <div class="row">
                <?php }
                ?>
                <div class="col-md-4">
                    <div class="form-group<?php if ($form->get($getServiceAttributes)->getMessages()) echo ' has-error'; ?>">
                        <div class="col-xs-12">
                            <?= $this->formLabel($form->get($getServiceAttributes)->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
                            <?= $this->formText($form->get($getServiceAttributes)->setAttribute('class', 'form-control')->setValue($valueAttribute)) ?>
                            <div id="helpBlock" class="help-block">
                                <?= $this->formElementErrors($form->get($getServiceAttributes)) ?>           
                            </div>
                        </div>
                    </div>
                </div>  
                <?php
                if ($i === 3) {
                    $i = 0;
                    ?>
                </div>
                <?php
            }
        }
        if ($i !== 3) {
            echo '</div>';
        }
        ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary"><?= $this->translate('Modifier') ?></button>
        <a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/service'); ?>">Annuler</a>
    </div>
</div>
<?=
$this->form()->closeTag()?>