<?php $this->headTitle($this->translate('Liste des profiles')); ?>

<h1><?= $this->translate('Liste des profiles') ?></h1>

<p>
    <a href="<?= $this->url('zfcadmin/profile/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter un nouveau profile') ?></a>

    <a href="<?= $this->url('zfcadmin/profile/profiling', array('action' => 'profiling')); ?>" class="btn btn-warning btn-xs"><?= $this->translate('Mettre à jour les profils des users - peut être très long !!!') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?>

<table class="table table-striped">  
    <tr>
        <th><?= $this->translate('Nom du profile') ?></th>
        <th><?= $this->translate('Label du profile') ?></th>
        <th><?= $this->translate('Priorité du profile') ?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($listProfiles as $profile) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($profile->getProfileName()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($profile->getProfileLibelle()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($profile->getProfilePriority()) ?>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/profile/show', ['id' => $this->escapeUrl($profile->getProfileId())]) ?>" class="btn btn-primary btn-xs">Détails</a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/profile/show/update', ['id' => $this->escapeUrl($profile->getProfileId())]) ?>" class="btn btn-warning btn-xs">Modifier</a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/profile/show/delete', ['id' => $this->escapeUrl($profile->getProfileId())]) ?>" class="btn btn-danger btn-xs">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>