<?php $this->headTitle($this->translate('Détails du profile')); ?>

<h2><?= $this->translate('Détails du profile') ?></h2>

<p>
    <?= $this->translate('Nom du profile :') ?> <?php echo $this->escapeHtml($profile->getProfileName()) ?>
</p>
<p>
    <?= $this->translate('Profile LDAP :') ?> <?php echo $this->escapeHtml($profile->getProfileLdap()) ?>
</p>
<p>
    <?= $this->translate('Libellé du profile :') ?> <?php echo $this->escapeHtml($profile->getProfileLibelle()) ?>
</p>
<p>
    <?= $this->translate('Description du profile :') ?> <?php echo $this->escapeHtml($profile->getProfileDescription()) ?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($profile->getProfileLastUpdate() != null) {
        echo $profile->getProfileLastUpdate()->format('d-m-Y H:i:s');
    } else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>

<a class="btn btn-danger" href="<?php echo $this->url('profile'); ?>"><?= $this->translate('Retour') ?></a>