<?php $this->headTitle($this->translate('Détails du profile')); ?>

<h2><?= $this->translate('Détails du profile') ?></h2>

<p>
    <?= $this->translate('Nom du profile :') ?> <?php echo $this->escapeHtml($profile->getProfileName()) ?>
</p>
<p>
    <?= $this->translate('Profile LDAP :') ?> <?php echo $this->escapeHtml($profile->getProfileLdap()) ?>
</p>
<p>
    <?= $this->translate('Libellé du profile :') ?> <?php echo $this->escapeHtml($profile->getProfileLibelle()) ?>
</p>
<p>
    <?= $this->translate('Description du profile :') ?> <?php echo $this->escapeHtml($profile->getProfileDescription()) ?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($profile->getProfileLastUpdate() != null) {
        echo $profile->getProfileLastUpdate()->format('d-m-Y H:i:s');
    } else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>

<?= $this->translate('Préférence :<br />') ?> 
<!--<dl class="dl-horizontal">-->
<?php
if ($preferenceAttribute) {
    foreach ($preferenceAttribute as $service) {
        ?>
        <table class="table">
             <caption><?= $service->{'serviceData'}->{'serviceName'} ?></caption>
            <tr class="warning">
                <th><?= $this->translate('Attribute') ?></th>
                <th><?= $this->translate('Value') ?></th>      
            </tr>    
            <?php
            foreach ($service->{'serviceAttributeData'} as $attribute) {
                echo '<tr><td class="success">' . $attribute->{'attributeName'} . '</td>';
                echo '<td>' . $attribute->{'attributeValue'} . '</td>';
            }
        }
        ?>
    </table>
    <?php
}
?> 
<!--</dl>-->

<a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/profile'); ?>"><?= $this->translate('Retour') ?></a>