<?php
$title = "Détails du profile";
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <b>Nom du profile :</b> <?php echo $this->escapeHtml($profile->getProfileName())?>
</p>
<p>
    <b>Profile Ldap :</b> <?php echo $this->escapeHtml($profile->getProfileLdap())?>
</p>
<p>
    <b>Libellé du profile :</b> <?php echo $this->escapeHtml($profile->getProfileLibelle())?>
</p>
<p>
    <b>Description du profile :</b> <?php echo $this->escapeHtml($profile->getProfileDescription())?>
</p>
<?php if($profile->getProfileLastUpdate() != null) :?>
<p>
    <b>Date de modification :</b> <?php echo $profile->getProfileLastUpdate()->format('Y-m-d H:i:s');?>
</p>
<?php endif; ?>