<?php
$title = 'Supprimer une action';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sur de supprimer le action
    '<?php echo $this->escapeHtml($action->getActionName()); ?>'?
</p>
<?php
$url = $this->url('action/delete', array(
    'id' => $this->id,
    ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $action->getActionId(); ?>" />
        <input class="btn btn-primary" type="submit" name="del" value="Oui" />
        <input class="btn btn-primary" type="submit" name="del" value="Non" />
    </div>
</form>