<?php $this->headTitle($this->translate('Liste des actions')); ?>

<h1><?= $this->translate('Liste des actions') ?></h1>

<p>
    <a href="<?php echo $this->url('zfcadmin/action/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter une nouvelle action') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?> 

<table class="table table-striped">  
    <tr>
        <th><?= $this->translate('Nom de l\'action') ?></th>
        <th><?= $this->translate('Libellé') ?></th>
        <th><?= $this->translate('Description') ?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($listActions as $action) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($action->getActionName()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($action->getActionLibelle()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($action->getActionDescription()) ?>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/action/show', ['id' => $this->escapeUrl($action->getActionId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/action/show/update', ['id' => $this->escapeUrl($action->getActionId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/action/show/delete', ['id' => $this->escapeUrl($action->getActionId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>