<?php
$title = 'Liste des actions';
$this->headTitle($title);
?>
<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?> 
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a href="<?php echo $this->url('action/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs">Ajouter une nouvelle action</a>
</p>
<table class="table table-striped">  
    <tr>
        <th>Nom de l'action</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($listActions as $action) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($action->getActionName()) ?>
            </td>
            <td>
                <a href="<?= $this->url('action/show', ['id' => $this->escapeUrl($action->getActionId())]) ?>" class="btn btn-primary btn-xs">Détails</a>
            </td>
            <td>
                <a href="<?= $this->url('action/update', ['id' => $this->escapeUrl($action->getActionId())]) ?>" class="btn btn-warning btn-xs">Modifier</a>
            </td>
            <td>
                <a href="<?= $this->url('action/delete', ['id' => $this->escapeUrl($action->getActionId())]) ?>" class="btn btn-danger btn-xs">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>