<?php
$title = "Détails d'une action";
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <b>Nom de l'action :</b> <?php echo $this->escapeHtml($action->getActionName())?>
</p>
<p>
    <b>Libellé de l'action :</b> <?php echo $this->escapeHtml($action->getActionLibelle())?>
</p>
<p>
    <b>Description d'une action :</b> <?php echo $this->escapeHtml($action->getActionDescription())?>
</p>
<?php if($action->getActionLastUpdate() != null) :?>
<p>
    <b>Date de modification :</b> <?php echo $action->getActionLastUpdate()->format('Y-m-d H:i:s');?>
</p>
<?php endif; ?>