<?php $this->headTitle($this->translate('Détails d\'une action')); ?>

<h2><?= $this->translate('Détails d\'une action') ?></h2>
<p>
    <?= $this->translate('Nom de l\'action :') ?> <?php echo $this->escapeHtml($action->getActionName())?>
</p>
<p>
    <?= $this->translate('Libellé de l\'action :') ?> <?php echo $this->escapeHtml($action->getActionLibelle())?>
</p>
<p>
    <?= $this->translate('Description de l\'action :') ?> <?php echo $this->escapeHtml($action->getActionDescription())?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($action->getActionLastUpdate() != null) {
        echo $action->getActionLastUpdate()->format('d-m-Y H:i:s');
    }
    else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>

<a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/action'); ?>"><?= $this->translate('Retour') ?></a>