<?php $this->headTitle($this->translate('Liste des contacts')); ?>

<h1><?= $this->translate('Liste des contacts') ?></h1>

<p>
    <a href="<?= $this->url('zfcadmin/contact/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter un nouveau contact') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m) : ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>  
    </div>
<?php endforeach; ?>

<table class="table table-striped">  
    <tr>
        <th><?=$this->translate('Nom du contact')?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($contacts as $contact) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($contact->getContactName()) ?>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/contact/show', ['id' => $this->escapeUrl($contact->getContactId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/contact/show/update', ['id' => $this->escapeUrl($contact->getContactId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/contact/show/delete', ['id' => $this->escapeUrl($contact->getContactId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
