<?php

namespace DoctrineORMModule\Proxy\__CG__\Ent\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EntAttribute extends \Ent\Entity\EntAttribute implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeId', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeName', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeLibelle', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeDescription', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeLastUpdate', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'fkSaAttributeSA');
        }

        return array('__isInitialized__', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeId', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeName', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeLibelle', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeDescription', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'attributeLastUpdate', '' . "\0" . 'Ent\\Entity\\EntAttribute' . "\0" . 'fkSaAttributeSA');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EntAttribute $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAttributeId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAttributeId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeId', array());

        return parent::getAttributeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeName($attributeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeName', array($attributeName));

        return parent::setAttributeName($attributeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeName', array());

        return parent::getAttributeName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeLibelle($attributeLibelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeLibelle', array($attributeLibelle));

        return parent::setAttributeLibelle($attributeLibelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeLibelle', array());

        return parent::getAttributeLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeDescription($attributeDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeDescription', array($attributeDescription));

        return parent::setAttributeDescription($attributeDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeDescription', array());

        return parent::getAttributeDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeLastUpdate($attributeLastUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeLastUpdate', array($attributeLastUpdate));

        return parent::setAttributeLastUpdate($attributeLastUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeLastUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeLastUpdate', array());

        return parent::getAttributeLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function addFkSaAttributeSA(\Ent\Entity\EntServiceAttribute $fkSaAttributeSA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFkSaAttributeSA', array($fkSaAttributeSA));

        return parent::addFkSaAttributeSA($fkSaAttributeSA);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFkSaAttributeSA(\Ent\Entity\EntServiceAttribute $fkSaAttributeSA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFkSaAttributeSA', array($fkSaAttributeSA));

        return parent::removeFkSaAttributeSA($fkSaAttributeSA);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkSaAttributeSA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkSaAttributeSA', array());

        return parent::getFkSaAttributeSA();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($hydrator, $owner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($hydrator, $owner));

        return parent::toArray($hydrator, $owner);
    }

}
