<?php

namespace DoctrineORMModule\Proxy\__CG__\Ent\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EntStructure extends \Ent\Entity\EntStructure implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureId', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureFatherid', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureType', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureCode', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureLibelle', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureIsValid', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureLastUpdate');
        }

        return array('__isInitialized__', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureId', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureFatherid', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureType', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureCode', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureLibelle', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureIsValid', '' . "\0" . 'Ent\\Entity\\EntStructure' . "\0" . 'structureLastUpdate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EntStructure $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setStructureId($structureId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructureId', array($structureId));

        return parent::setStructureId($structureId);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getStructureId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureId', array());

        return parent::getStructureId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructureFatherid($structureFatherid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructureFatherid', array($structureFatherid));

        return parent::setStructureFatherid($structureFatherid);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureFatherid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureFatherid', array());

        return parent::getStructureFatherid();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructureType($structureType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructureType', array($structureType));

        return parent::setStructureType($structureType);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureType', array());

        return parent::getStructureType();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructureCode($structureCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructureCode', array($structureCode));

        return parent::setStructureCode($structureCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureCode', array());

        return parent::getStructureCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructureLibelle($structureLibelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructureLibelle', array($structureLibelle));

        return parent::setStructureLibelle($structureLibelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureLibelle', array());

        return parent::getStructureLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructureIsValid($structureIsValid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructureIsValid', array($structureIsValid));

        return parent::setStructureIsValid($structureIsValid);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureIsValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureIsValid', array());

        return parent::getStructureIsValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructureLastUpdate($structureLastUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructureLastUpdate', array($structureLastUpdate));

        return parent::setStructureLastUpdate($structureLastUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructureLastUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructureLastUpdate', array());

        return parent::getStructureLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($hydrator, $owner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($hydrator, $owner));

        return parent::toArray($hydrator, $owner);
    }

}
