<?php $this->headTitle($this->translate('Ajout une permission')); ?>
<h2><?=$this->translate('Ajouter une permission')?></h2>
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate')) ?>
<div class="form-group<?php if ($form->get('name')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('name')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('name')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('name')) ?>           
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary"><?= $this->translate('Ajouter') ?></button>
        <a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/permission'); ?>"><?= $this->translate('Annuler') ?></a>
    </div>
</div>
<?=$this->form()->closeTag()?>
