<?php
$title = 'Liste des attributs';
$this->headTitle($title);
?>
<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?> 
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a href="<?php echo $this->url('attribute/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs">Ajouter un nouvel attribut</a>
</p>
<table class="table table-striped">  
    <tr>
        <th>Nom de l'attribut</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($listAttributes as $attribute) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($attribute->getAttributeName()) ?>
            </td>
            <td>
                <a href="<?= $this->url('attribute/show', ['id' => $this->escapeUrl($attribute->getAttributeId())]) ?>" class="btn btn-primary btn-xs">Détails</a>
            </td>
            <td>
                <a href="<?= $this->url('attribute/update', ['id' => $this->escapeUrl($attribute->getAttributeId())]) ?>" class="btn btn-warning btn-xs">Modifier</a>
            </td>
            <td>
                <a href="<?= $this->url('attribute/delete', ['id' => $this->escapeUrl($attribute->getAttributeId())]) ?>" class="btn btn-danger btn-xs">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>