<?php $this->headTitle($this->translate('Liste des attributs')); ?>

<h1><?= $this->translate('Liste des attributs') ?></h1>

<p>
    <a href="<?= $this->url('zfcadmin/attribute/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter un nouvel attribut') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?> 
<div class="input-group col-lg-4 pull-right">
    <input id="filterTable" type="text" class="form-control" placeholder="<?= $this->translate('Would you like my attribute on your property ?') ?>">
    <span class="input-group-addon"><?= $this->translate('Get it !') ?></span>
</div>
<table class="table table-striped">  
    <thead>
        <tr>
            <th><?= $this->translate('Nom de l\'attribut') ?></th>
            <th><?= $this->translate('Libellé') ?></th>
            <th><?= $this->translate('Description') ?></th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>        
        </tr>
    </thead>
    <tbody  class="searchable">
        <?php foreach ($listAttributes as $attribute) : ?>
            <tr>
                <td>
                    <?= $this->escapeHtml($attribute->getAttributeName()) ?>
                </td>
                <td>
                    <?= $this->escapeHtml($attribute->getAttributeLibelle()) ?>
                </td>
                <td>
                    <?= $this->escapeHtml($attribute->getAttributeDescription()) ?>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/attribute/show', ['id' => $this->escapeUrl($attribute->getAttributeId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/attribute/show/update', ['id' => $this->escapeUrl($attribute->getAttributeId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
                </td>
                <td>
                    <a href="<?= $this->url('zfcadmin/attribute/show/delete', ['id' => $this->escapeUrl($attribute->getAttributeId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>