<?php $this->headTitle($this->translate('Détails d\'un attribut')); ?>

<h2><?= $this->translate('Détails d\'un attribut') ?></h2>
<p>
    <?= $this->translate('Nom du attribute :') ?> <?= $this->escapeHtml($attribute->getAttributeName()) ?>
</p>
<p>
    <?= $this->translate('Libellé du attribute :') ?> <?= $this->escapeHtml($attribute->getAttributeLibelle()) ?>
</p>
<p>
    <?= $this->translate('Description du attribute :') ?> <?php echo $this->escapeHtml($attribute->getAttributeDescription()) ?>
</p>
<p>
    <?= $this->translate('Liste de l\'attribut :') ?> 
    <?php
    if ($attribute->getFkAttributeListtype()) {
        echo $this->escapeHtml($attribute->getFkAttributeListtype()->getListtypeLibelle());
    }
    else{
        echo $this->translate('Pas de liste attachée');
    }
    ?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($attribute->getAttributeLastUpdate() != null) {
        echo $attribute->getAttributeLastUpdate()->format('d-m-Y H:i:s');
    } else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>

<a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/attribute'); ?>"><?= $this->translate('Retour') ?></a>