<?php $this->headTitle($this->translate('Modifier un item dans la liste')); ?>

<h2><?= $this->translate('Modifier un item dans la liste') ?></h2>
<?= $this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate')) ?>
<div class="form-group<?php if ($form->get('listLibelle')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('listLibelle')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('listLibelle')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('listLibelle')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('fkListType')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('fkListType')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?php
        echo $this->formSelect($form->get('fkListType')->setLabelAttributes(['class' => '']))
        ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('fkListType')) ?>           
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary"><?= $this->translate('Modifier') ?></button>
        <a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/list'); ?>"><?= $this->translate('Annuler') ?></a>
    </div>
</div>
<?=
$this->form()->closeTag()?>