<?php
$title = 'Demandez de l\'aide';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate'))?>
<div class="form-group">
    <div class="col-sm-10">
        <p><strong>Votre adresse e-mail :</strong> <?php echo $infoUser[0]['mail'][0]; ?></p>
    </div>
</div>
<div class="form-group <?php if($form->get('contactDescription')) ; ?>">
    <?=$this->formLabel($form->get('contactDescription')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?=$this->formSelect($form->get('contactDescription')->setAttribute('class', 'form-control'))?>
    </div>
</div>
<div class="form-group <?php if($form->get('message')->getMessages()) echo "has-error"; ?>">
    <?=$this->formLabel($form->get('message')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?=$this->formElement($form->get('message')->setAttribute('class', 'form-control'))?>
    </div>
    <span class="help-block">
        <?=$this->formElementErrors($form->get('message'))?>
    </span>
</div>
<div class="form-group <?php if($form->get('image-file')->getMessages()) echo "has-error"; ?>">
    <?=$this->formLabel($form->get('image-file')->setLabelAttributes(array('class' => 'col-sm-2 control-label')))?>
    <div class="col-sm-10">
        <?=$this->formFile($form->get('image-file'))?>
    </div>
    <span class="help-block">
        <?=$this->formElementErrors($form->get('image-file'))?>
    </span>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
