<?php $this->headTitle($this->translate('Ajout d\'un log')); ?>
<h2><?php echo $this->escapeHtml('Ajout d\'un log'); ?></h2>
<?= $this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate')) ?>

<div class="form-group<?php if ($form->get('logLogin')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('logLogin')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('logLogin')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('logLogin')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('logOnline')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('logOnline')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formDateTime($form->get('logOnline')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('logOnline')) ?>           
    </div>
</div>
<div class="form-group<?php if ($form->get('logOffline')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('logOffline')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formDateTime($form->get('logOffline')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('logOffline')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('logSession')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('logSession')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('logSession')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('logSession')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('logIp')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('logIp')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('logIp')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('logIp')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('logUseragent')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('logUseragent')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formTextarea($form->get('logUseragent')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('logUseragent')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('fkLogUser')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('fkLogUser')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?php
        echo $this->formSelect($form->get('fkLogUser')->setLabelAttributes(['class' => '']))
        ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('fkLogUser')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('fkLogAction')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('fkLogAction')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?php
        echo $this->formSelect($form->get('fkLogAction')->setLabelAttributes(['class' => '']))
        ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('fkLogAction')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('fkLogModule')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('fkLogModule')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?php
        echo $this->formSelect($form->get('fkLogModule')->setLabelAttributes(['class' => '']))
        ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('fkLogModule')) ?>           
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary"><?= $this->translate('Ajouter') ?></button>
        <a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/log'); ?>"><?= $this->translate('Annuler') ?></a>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>