<?php
    $title = "Ajout d'un role";
    $this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<!-- roleName -->
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate'))?>
<div class="form-group<?php if($form->get('roleName')->getMessages()) echo ' has-error'; ?>">
    <?=$this->formLabel($form->get('roleName')->setLabelAttributes(['class' => 'col-sm-2 control-label']))?>
    <div class="col-sm-10">
        <?=$this->formText($form->get('roleName')->setAttribute('class', 'form-control'))?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?=$this->formElementErrors($form->get('roleName'))?>           
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>