<?php
$title = 'Supprimer un role';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sur de supprimer le role
    '<?php echo $this->escapeHtml($this->role->getName()); ?>'?
</p>
<?php
    $url = $this->url('role/delete', array('id' => $this->id));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $this->role->getId(); ?>" />
        <input class="btn btn-primary" type="submit" name="del" value="Oui" />
        <input class="btn btn-primary" type="submit" name="del" value="Non" />
    </div>
</form>