<?php $this->headTitle($this->translate('Liste des rôles')); ?>

<h1><?= $this->translate('Liste des rôles') ?></h1>

<p>
    <a href="<?php echo $this->url('zfcadmin/role/add'); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter une nouveau role') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m) : ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?>

<table class="table table-striped"> 
    <tr>
        <th><?=$this->translate('Nom du role')?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($roles as $role) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($role->getName()) ?>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/role/show', ['id' => $this->escapeUrl($role->getId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/role/show/update', ['id' => $this->escapeUrl($role->getId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/role/show/delete', ['id' => $this->escapeUrl($role->getId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>