<?php $this->headTitle($this->translate('Détails d\'un role')); ?>

<h2><?= $this->translate('Détails d\'un role') ?></h2>

<p>
    <?= $this->translate('Role :') ?> <?= $this->escapeHtml($role->getName()) ?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php 
    if ($role->getlastUpdate() != null) {
        echo $role->getlastUpdate()->format('d-m-Y H:i:s');
    }
    ?>
</p>

<p>
    <?= $this->translate('Rôles enfant :') ?> 
    <?php
    foreach ($role->getChildren() as $child) {
        if ($child->getName()) :
            echo $this->escapeHtml($child->getName()) . ' - ';
        endif;
    }
    ?>
</p>

<p>
    <?= $this->translate('Permissions :') ?> 
    <?php
    foreach ($role->getPermissions() as $permission) {
        if ($permission->getName()) :
            echo $this->escapeHtml($permission->getName()) . ' - ';
        endif;
    }
    ?>
</p>

<a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/role'); ?>"><?= $this->translate('Retour') ?></a>