<?php $this->headTitle($this->translate('Modifier un role')); ?>

<h2><?= $this->translate('Modifier un role') ?></h2>
<?= $this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate')) ?>
<div class="form-group<?php if ($form->get('name')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('name')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('name')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('name')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('children')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('children')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <div class="checkbox">
            <?php
            $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
            echo $this->formMultiCheckbox($form->get('children')->setLabelAttributes(['class' => '']))
            ?>
        </div>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('children')) ?>           
    </div>
</div>

<div class="form-group<?php if ($form->get('permissions')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('permissions')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <div class="checkbox">
            <?php
            $this->formMultiCheckbox()->setSeparator('</div><div class="checkbox">');
            echo $this->formMultiCheckbox($form->get('permissions')->setLabelAttributes(['class' => '']))
            ?>
        </div>
    </div>
    <div id="helpBlock" class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('permissions')) ?>           
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary"><?= $this->translate('Modifier') ?></button>
        <a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/role'); ?>"><?= $this->translate('Annuler') ?></a>
    </div>
</div>
<?=$this->form()->closeTag()?>