<?php
$title = "Ajout d'un status";
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<?=$this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate'))?>
<div class="form-group<?php if($form->get('statusName')->getMessages()) echo ' has-error'; ?>">
    <?=$this->formLabel($form->get('statusName')->setLabelAttributes(['class' => 'col-sm-2 control-label']))?>
    <div class="col-sm-10">
        <?=$this->formText($form->get('statusName')->setAttribute('class', 'form-control'))?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?=$this->formElementErrors($form->get('statusName'))?>           
    </div>
</div>
<div class="form-group<?php if($form->get('statusLibelle')->getMessages()) echo ' has-error'; ?>">
    <?=$this->formLabel($form->get('statusLibelle')->setLabelAttributes(['class' => 'col-sm-2 control-label']))?>
    <div class="col-sm-10">
        <?=$this->formText($form->get('statusLibelle')->setAttribute('class', 'form-control'))?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?=$this->formElementErrors($form->get('statusLibelle'))?>           
    </div>
</div>
<div class="form-group<?php if($form->get('statusDescription')->getMessages()) echo ' has-error'; ?>">
    <?=$this->formLabel($form->get('statusDescription')->setLabelAttributes(['class' => 'col-sm-2 control-label']))?>
    <div class="col-sm-10">
        <?=$this->formTextarea($form->get('statusDescription')->setAttribute('class', 'form-control'))?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?=$this->formElementErrors($form->get('statusDescription'))?>           
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>