<?php $this->headTitle($this->translate('Liste des status')); ?>

<h1><?= $this->translate('Liste des status') ?></h1>

<p>
    <a href="<?php echo $this->url('status/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs"><?= $this->translate('Ajouter un nouveau status') ?></a>
</p>

<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?> 

<table class="table table-striped">  
    <tr>
        <th><?= $this->translate('Nom du status') ?></th>
        <th><?= $this->translate('Libellé') ?></th>
        <th><?= $this->translate('Description') ?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>        
    </tr>
    <?php foreach ($listStatus as $status) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($status->getStatusName()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($status->getStatusLibelle()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($status->getStatusDescription()) ?>
            </td>
            <td>
                <a href="<?= $this->url('status/show', ['id' => $this->escapeUrl($status->getStatusId())]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Détails') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('status/show/update', ['id' => $this->escapeUrl($status->getStatusId())]) ?>" class="btn btn-warning btn-xs"><?= $this->translate('Modifier') ?></a>
            </td>
            <td>
                <a href="<?= $this->url('status/show/delete', ['id' => $this->escapeUrl($status->getStatusId())]) ?>" class="btn btn-danger btn-xs"><?= $this->translate('Supprimer') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>