<?php
$title = "Détails du status";
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <b>Nom du status :</b> <?php echo $this->escapeHtml($status->getStatusName())?>
</p>
<p>
    <b>Libellé du status :</b> <?php echo $this->escapeHtml($status->getStatusLibelle())?>
</p>
<p>
    <b>Description du status :</b> <?php echo $this->escapeHtml($status->getStatusDescription())?>
</p>
<?php if($status->getStatusLastUpdate() != null) :?>
<p>
    <b>Date de modification :</b> <?php echo $status->getStatusLastUpdate()->format('Y-m-d H:i:s');?>
</p>
<?php endif; ?>