<?php $this->headTitle($this->translate('Détails d\'un status')); ?>

<h2><?= $this->translate('Détails d\'un status') ?></h2>
<p>
    <?= $this->translate('Nom du status :') ?> <?php echo $this->escapeHtml($status->getStatusName())?>
</p>
<p>
    <?= $this->translate('Libellé du status :') ?> <?php echo $this->escapeHtml($status->getStatusLibelle())?>
</p>
<p>
    <?= $this->translate('Description du status :') ?> <?php echo $this->escapeHtml($status->getStatusDescription())?>
</p>

<p>
    <?= $this->translate('Dernière mise à jour :') ?> 
    <?php
    if ($status->getStatusLastUpdate() != null) {
        echo $status->getStatusLastUpdate()->format('d-m-Y H:i:s');
    }
    else {
        echo $this->translate('Aucune mise à jour');
    }
    ?>
</p>

<a class="btn btn-danger" href="<?php echo $this->url('status'); ?>"><?= $this->translate('Retour') ?></a>