<?php
$title = "Ajout d'une version";
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<!-- Version -->
<?= $this->form()->openTag($form->setAttribute('class', 'form-horizontal')->setAttribute('novalidate', 'novalidate')) ?>
<div class="form-group<?php if ($form->get('version')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('version')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formText($form->get('version')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('version')) ?>           
    </div>
</div>

<!-- Commentaire -->
<div class="form-group<?php if ($form->get('versionCommentaire')->getMessages()) echo ' has-error'; ?>">
    <?= $this->formLabel($form->get('versionCommentaire')->setLabelAttributes(['class' => 'col-sm-2 control-label'])) ?>
    <div class="col-sm-10">
        <?= $this->formTextarea($form->get('versionCommentaire')->setAttribute('class', 'form-control')) ?>
    </div>
    <div id="helpBlock " class="help-block col-sm-offset-2 col-sm-10">
        <?= $this->formElementErrors($form->get('versionCommentaire')) ?>           
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Ajouter</button>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url('version', array('action' => 'index')); ?>" class="btn btn-primary">Annuler</a>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>