<?php
    $title = 'Liste des versions ENT';
    $this->headTitle($title);
?>
<?php foreach ($this->flashMessenger()->getSuccessMessages() as $m): ?>
    <div class="alert alert-success" role="alert">
        <?= $this->translate($m) ?>
    </div>  
<?php endforeach; ?> 
<h2><?php echo $this->escapeHtml($title); ?></h2>

<p>
    <a href="<?php echo $this->url('zfcadmin/version/add', array('action' => 'add')); ?>" class="btn btn-primary btn-xs">Ajouter une nouvelle version</a>
</p>
<table class="table table-striped">  
    <tr>
        <th>Version</th>
        <th>Date</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($listVersions as $version) : ?>
        <tr>
            <td>
                <?= $this->escapeHtml($version->getVersion()) ?>
            </td>
            <td>
                <?= $this->escapeHtml($version->getVersionDate()->format('Y-m-d H:i:s')) ?>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/version/show', ['id' => $this->escapeUrl($version->getId())]) ?>" class="btn btn-primary btn-xs">Détails</a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/version/show/update', ['id' => $this->escapeUrl($version->getId())]) ?>" class="btn btn-warning btn-xs">Modifier</a>
            </td>
            <td>
                <a href="<?= $this->url('zfcadmin/version/show/delete', ['id' => $this->escapeUrl($version->getId())]) ?>" class="btn btn-danger btn-xs">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>